from .ai_engine import ai_engine
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from io import BytesIO
import json
import re

def generate_learning_path(data):
    # Prompt 4: Personalized Learning Path Generator Prompt (Enhanced for JSON)
    base_prompt = """
    You are an AI Personalized Learning Path Generator.

    User Inputs:
    - Course Name: {course_name}
    - Current Skills: {current_skills}
    - Learning Duration: {duration}
    - Experience Level: {level}

    Generate a professional JSON object with the following structure (do NOT return markdown, just the raw JSON string).

    IMPORTANT: Keep descriptions CONCISE to avoid response truncation.

    {{
        "overview": "Brief executive summary.",
        "weekly_schedule": [
            {{
                "week": "Week 1",
                "topic": "Topic Name",
                "details": "Brief explanation of concepts.",
                "daily_breakdown": ["Day 1: Topic A", "Day 2: Lab B", "Day 3: Deep Dive C", "Day 4: Project D", "Day 5: Review"],
                "key_outcomes": ["Skill 1", "Skill 2"]
            }},
            ...
        ],
        "resources": [
            {{ "name": "Resource Title", "type": "Book/Website", "link": "URL" }}
        ],
        "next_steps": "Actionable next steps."
    }}

    Constraints:
    - STRICTLY NO YOUTUBE LINKS. Use only high-quality documentation.
    - Provide a Daily Breakdown efficiently (short phrases).
    - Content must be technical and suitable for '{level}'.
    - Ensure 'weekly_schedule' fits within '{duration}'.
    """

    prompt = base_prompt.format(
        course_name=data['course_name'],
        current_skills=data.get('current_skills', 'None'),
        duration=data.get('duration', 'Flexible'),
        level=data.get('level', 'Beginner')
    )

    raw_response = ai_engine.generate_response(prompt)

    # Simple cleanup to ensure JSON parsing
    # Use robust parsing from resume_parser
    from .resume_parser import parse_ai_json
    parsed_data = parse_ai_json(raw_response)

    if parsed_data:
        return parsed_data
    else:
        print(f"JSON Parsing Failed. Raw: {raw_response}")
        return {
            "overview": "Could not parse AI response as JSON. Please try again.",
            "weekly_schedule": [{"week": "Error", "topic": "Raw Output", "details": raw_response, "daily_breakdown": [], "key_outcomes": []}],
            "resources": [],
            "next_steps": "Please try again."
        }

def create_word_doc(roadmap_data, course_name):
    # Logic implemented via python-docx using structured data
    doc = Document()

    # Title
    title = doc.add_heading(f'Learning Roadmap: {course_name}', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Overview
    doc.add_heading('Overview', level=1)
    if isinstance(roadmap_data, str):
        # Handle case where roadmap is just string (legacy or fallback)
        doc.add_paragraph(roadmap_data)
        return save_doc(doc)

    doc.add_paragraph(roadmap_data.get('overview', ''))

    # Weekly Schedule
    doc.add_heading('Weekly Schedule', level=1)
    # Weekly Schedule - Detailed
    doc.add_heading('Curriculum Schedule', level=1)

    for item in roadmap_data.get('weekly_schedule', []):
        # Week Header
        week_header = doc.add_heading(f"{item.get('week', '')}: {item.get('topic', '')}", level=2)

        # Details
        doc.add_paragraph(item.get('details', ''))

        # Daily Breakdown
        if item.get('daily_breakdown'):
            doc.add_heading('Daily Focus:', level=3)
            for day in item.get('daily_breakdown', []):
                doc.add_paragraph(day, style='List Bullet')

        # Key Outcomes
        if item.get('key_outcomes'):
            p = doc.add_paragraph()
            p.add_run('Key Outcomes: ').bold = True
            p.add_run(", ".join(item.get('key_outcomes', [])))

        doc.add_paragraph() # Spacer

    # Resources
    doc.add_heading('Recommended Resources', level=1)
    for res in roadmap_data.get('resources', []):
        p = doc.add_paragraph(style='List Bullet')
        run = p.add_run(f"{res.get('name')} ({res.get('type')})")
        run.font.bold = True
        p.add_run(f": {res.get('link')}")

    # Next Steps
    doc.add_heading('Next Steps', level=1)
    doc.add_paragraph(roadmap_data.get('next_steps', ''))

    # Footer
    section = doc.sections[0]
    footer = section.footer
    p = footer.paragraphs[0]
    p.text = "Generated by Wayfinder.ai - Your Personal AI Tutor"
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    return save_doc(doc)

def save_doc(doc):
    f = BytesIO()
    doc.save(f)
    f.seek(0)
    return f
